#!/bin/sh

. ./config

http http://localhost/en/data/api/3/action/group_create name=accessibility                      title="Accessibility"                       image_url=$CATEGORY_IMAGE_URL/accessibility.png                      Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=air-quality-health-index           title="Air Quality Health Index"            image_url=$CATEGORY_IMAGE_URL/air-quality-health-index.png           Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=buildings                          title="Buildings"                           image_url=$CATEGORY_IMAGE_URL/buildings.png                          Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=charitable-fund-raising-activities title="Charitable Fund-Raising Activities"  image_url=$CATEGORY_IMAGE_URL/charitable-fund-raising-activities.png Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=food-and-environmental-hygiene     title="Food and Environmental Hygiene"      image_url=$CATEGORY_IMAGE_URL/food-and-environmental-hygiene.png     Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=geospatial-data                    title="Geospatial Data"                     image_url=$CATEGORY_IMAGE_URL/geospatial-data.png                    Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=image-resources                    title="Image Resources"                     image_url=$CATEGORY_IMAGE_URL/image-resources.png                    Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=law-and-order                      title="Law and Order"                       image_url=$CATEGORY_IMAGE_URL/law-and-order.png                      Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=marine                             title="Marine"                              image_url=$CATEGORY_IMAGE_URL/marine.png                             Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=news-and-information               title="News and Information"                image_url=$CATEGORY_IMAGE_URL/news-and-information.png               Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=population-census-statistics       title="Population Census Statistics"        image_url=$CATEGORY_IMAGE_URL/population-census-statistics.png       Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=property-market-statistics         title="Property Market Statistics"          image_url=$CATEGORY_IMAGE_URL/property-market-statistics.png         Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=public-transport                   title="Public Transport"                    image_url=$CATEGORY_IMAGE_URL/public-transport.png                   Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=real-time-traffic-data             title="Real-Time Traffic Data"              image_url=$CATEGORY_IMAGE_URL/real-time-traffic-data.png             Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=water-quality                      title="Water Quality"                       image_url=$CATEGORY_IMAGE_URL/water-quality.png                      Authorization:$API_KEY_EN
http http://localhost/en/data/api/3/action/group_create name=weather-data                       title="Weather Data"                        image_url=$CATEGORY_IMAGE_URL/weather-data.png                       Authorization:$API_KEY_EN

http http://localhost/tc/data/api/3/action/group_create name=accessibility                      title="şı¡éşıç¤™äşıå®şı           image_url=$CATEGORY_IMAGE_URL/accessibility.png                      Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=air-quality-health-index           title="ç©ºæ°£è³ªçşışı¥åº·şı‡æ•¸"     image_url=$CATEGORY_IMAGE_URL/air-quality-health-index.png           Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=buildings                          title="å±‹åşı"                 image_url=$CATEGORY_IMAGE_URL/buildings.png                          Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=charitable-fund-raising-activities title="şı²æ‰¹şı†çşışıˆåşıç±Œæ¬¾æ´»åşı" image_url=$CATEGORY_IMAGE_URL/charitable-fund-raising-activities.png Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=food-and-environmental-hygiene     title="é£Ÿç‰©şıŠç’°å¢ƒèşışışı       image_url=$CATEGORY_IMAGE_URL/food-and-environmental-hygiene.png     Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=geospatial-data                    title="şı°çşıç©ºéşışı¸æşı"         image_url=$CATEGORY_IMAGE_URL/geospatial-data.png                    Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=image-resources                    title="å½±åşıè³‡æşı"             image_url=$CATEGORY_IMAGE_URL/image-resources.png                    Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=law-and-order                      title="æ³•åşışıŠæ²»å®şı           image_url=$CATEGORY_IMAGE_URL/law-and-order.png                      Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=marine                             title="æµ·äşı"                 image_url=$CATEGORY_IMAGE_URL/marine.png                             Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=news-and-information               title="şı°èşışıŠèşıè¨şı           image_url=$CATEGORY_IMAGE_URL/news-and-information.png               Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=population-census-statistics       title="äººå£şı®æŸ¥çµ±èşıè³‡æşı"     image_url=$CATEGORY_IMAGE_URL/population-census-statistics.png       Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=property-market-statistics         title="şı©æ¥­å¸‚å ´çµ±èşıè³‡æşı"     image_url=$CATEGORY_IMAGE_URL/property-market-statistics.png         Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=public-transport                   title="şı¬å…±äº¤éşı"             image_url=$CATEGORY_IMAGE_URL/public-transport.png                   Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=real-time-traffic-data             title="å¯¦æşıäº¤éşıè³‡æşı"         image_url=$CATEGORY_IMAGE_URL/real-time-traffic-data.png             Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=water-quality                      title="æ°´è³ª"                 image_url=$CATEGORY_IMAGE_URL/water-quality.png                      Authorization:$API_KEY_TC
http http://localhost/tc/data/api/3/action/group_create name=weather-data                       title="å¤©æ°£è³‡èşı"             image_url=$CATEGORY_IMAGE_URL/weather-data.png                       Authorization:$API_KEY_TC

http http://localhost/sc/data/api/3/action/group_create name=accessibility                      title="şı éşıç¢äşıå®şı           image_url=$CATEGORY_IMAGE_URL/accessibility.png                      Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=air-quality-health-index           title="ç©ºæşıè´¨çşışı¥åº·şı‡æ•°"     image_url=$CATEGORY_IMAGE_URL/air-quality-health-index.png           Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=buildings                          title="å±‹åşı"                 image_url=$CATEGORY_IMAGE_URL/buildings.png                          Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=charitable-fund-raising-activities title="şı·æ‰¹şı†çşışıˆåşıç­¹æ¬¾æ´»åŠ¨" image_url=$CATEGORY_IMAGE_URL/charitable-fund-raising-activities.png Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=food-and-environmental-hygiene     title="é£Ÿç‰©şıŠç¯å¢ƒå«şışı       image_url=$CATEGORY_IMAGE_URL/food-and-environmental-hygiene.png     Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=geospatial-data                    title="şı°çşıç©ºé—´şı°æ®"         image_url=$CATEGORY_IMAGE_URL/geospatial-data.png                    Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=image-resources                    title="å½±åşıèµ„æşı"             image_url=$CATEGORY_IMAGE_URL/image-resources.png                    Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=law-and-order                      title="æ³•åşışıŠæ²»å®şı           image_url=$CATEGORY_IMAGE_URL/law-and-order.png                      Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=marine                             title="æµ·äşı"                 image_url=$CATEGORY_IMAGE_URL/marine.png                             Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=news-and-information               title="şı°é—»şıŠèşıè®şı           image_url=$CATEGORY_IMAGE_URL/news-and-information.png               Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=population-census-statistics       title="äººå£şı®æŸ¥ç»Ÿè®¡èµ„æşı"     image_url=$CATEGORY_IMAGE_URL/population-census-statistics.png       Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=property-market-statistics         title="şı©äşıå¸‚åœºç»Ÿè®¡èµ„æşı"     image_url=$CATEGORY_IMAGE_URL/property-market-statistics.png         Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=public-transport                   title="şı¬å…±äº¤éşı"             image_url=$CATEGORY_IMAGE_URL/public-transport.png                   Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=real-time-traffic-data             title="å®æ—¶äº¤éşıèµ„æşı"         image_url=$CATEGORY_IMAGE_URL/real-time-traffic-data.png             Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=water-quality                      title="æ°´è´¨"                 image_url=$CATEGORY_IMAGE_URL/water-quality.png                      Authorization:$API_KEY_SC
http http://localhost/sc/data/api/3/action/group_create name=weather-data                       title="å¤©æşıèµ„è®¯"             image_url=$CATEGORY_IMAGE_URL/weather-data.png                       Authorization:$API_KEY_SC
